import { Map, List } from "immutable";

export default Map({
  user: Map(undefined),
  pruebas: Map(),
  groupData: List(),
  search: "",
  loading: false,
  allResult: Map(),
  testMessage: Map({
    recomendacion: `Consultar Nutricionista Realizar trabajos con pesasbajo supervisión de unexperto en Educación física.`,
    recomendacion2: `Mantener tu peso`,
    recomendacion3: `Consultar Nutricionista, Realizar ejercicio Aeróbico bajo supervisión de un experto en Educación Física de larga duración y de baja  intensidad, ejemplo caminar,  trotar, nadar, andar en bicicleta.`,
    recomendacion4: "Consultar a un medico",
    peso1: "Peso insuficiente",
    peso2: "Normopeso",
    peso3: "Sobrepeso grado I",
    peso4: "Sobrepeso grado II (preobesidad)",
    peso5: "Obesidad de tipo I",
    peso6: "Obesidad de tipo II",
    peso7: "Obesidad de tipo III (mórbida)",
    peso8: "Obesidad de tipo IV (extrema",
    ICC1: "Muy Bajo",
    ICC2: "Riesgo Cardiovascular Bajo",
    ICC3: "Riesgo Cardiovascular Alto",
    TA1: "optima",
    TA2: "Normal",
    TA3: "Hipertension grado 1",
    TA4: "Hipertension grado 2",
    TA5: "Hipertension grado 3",
    TA6: "Hipertension Sistolica Aisladaa",
    FC1: "Normal",
    FC2: "Braquicardia Sinusual",
    FC3: "Taquicardia",
    FC4: "Bradicardia por bloqueo auriculo-ventricular completo.",
    FR1: "Taquipnea",
    FR2: "Bradipnea",
    evaluacion1: "Muy Bajo",
    evaluacion2: "Bajo",
    evaluacion3: "Deficiente",
    evaluacion4: "Promedio",
    evaluacion5: "Buena",
    evaluacion6: "Excelente",
    evaluacion7: "Superior"
  })
});
